### ISSUE TITLE
tail recursion

### ISSUE THREAD

**Issue by marcellourbani** [well-typed/unfolder#2]
Nice video!
There's one thing that bothers me:
your definition of unfoldr' seems non tail recursive to me, as you need the tail to append the current value to
```haskell
unfoldr' :: (s -> Maybe (a, s)) -> s -> [a]
unfoldr' gen s =
  case gen s of
    Nothing      -> []
    Just (a, s') -> a : unfoldr'' gen s'
```

But tested this one seems to have exactly the same performance, and the stack doesn't blow generating a 10000000000 long list:
```haskell
unfoldr'' :: (s -> Maybe (a, s)) -> s -> [a]
unfoldr'' gen = go []  where
    go acc cur =
        case gen cur of
            Nothing      -> acc
            Just (a, s') -> go (a:acc) s'
```
Is GHC smart enough to optimise it away? Or am I missing something?

**Comment by kosmikus** [comment]
Thanks for the comment!

Have you tried running the `fibs` example with your version of `unfoldr''`?

The short answer is: you definitely don't want `unfoldr` to be tail-recursive.

Perhaps we should do an episode on the role of tail recursion in Haskell at some point as well.

**Comment by marcellourbani** [comment]
Oops!
Thanks for the reply, looking forward for the episode :)
